# Generated by Django 4.2.2 on 2024-06-29 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='project',
        ),
    ]
